### ISSUE TITLE
Regarding the issue of dataset production

### ISSUE THREAD

**Issue by Jingranxia** [caijunhao/ov9d#2]
Hello author, may I ask if your dataset was created using the NOCS data method in Professor Wang He's article from 2019

**Comment by caijunhao** [comment]
The dataset is generated similar to the procedure illustrated in this [page](https://dlr-rm.github.io/BlenderProc/examples/datasets/bop_challenge/README.html) and is organized in BOP format. So, it's different to the method proposed by NOCS.
